plugins {
    id 'java'
}

group = 'pl.khuzzuk'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.jthink:jaudiotagger:3.0.1'
    implementation 'org.apache.lucene:lucene-core:10.4.0'
    implementation 'org.apache.lucene:lucene-analysis-common:10.4.0'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
