#Settings
#Fri May 29 10:59:54 CEST 2026
indexed.paths=C\:\\java\\temp\\test_files3;C\:\\java\\temp\\test_files2;C\:\\java\\temp\\test_files
last.choosen.path=C\:\\java\\temp\\test_files
last.playlist=
last.tree.position=
track.columns=title\:171;album\:153;composer\:167;rating\:100;mood\:227;movement\:315;occasion\:314
window.height=1694
window.maximize=false
window.width=3086
window.x=-7
window.y=-7
