#Settings
#Thu May 28 08:59:59 CEST 2026
indexed.paths=C\:\\java\\temp\\test_files3;C\:\\java\\temp\\test_files2;C\:\\java\\temp\\test_files
last.choosen.path=C\:\\java\\temp\\test_files
last.playlist=
last.tree.position=
window.height=1035
window.maximize=false
window.width=2270
window.x=278
window.y=150
