#Settings
#Wed Jun 03 08:51:20 CEST 2026
indexed.paths=
last.choosen.path=
last.playlist=D\:\\ToDelete\\test_files3\\Ad Astra\\05 - Max Richter - A Trip To The Moon.mp3;D\:\\ToDelete\\test_files3\\Ad Astra\\01 - Max Richter - To The Stars.mp3;D\:\\ToDelete\\test_files3\\Ad Astra\\23 - Lorne Balfe - Space Journey.mp3;D\:\\ToDelete\\test_files3\\Angels 2\\Angels II 31.mp3
last.playlist.position=2
last.tracks.filter.tag=mood
last.tree.position=D\:\\ToDelete\\test_files3\\Angels 2
track.columns=title\:390;album\:308;composer\:192;rating\:129;mood\:156;tempo\:152;occasion\:175;duration\:132
track.sort=rating\:descending
window.height=1694
window.maximize=false
window.width=3086
window.x=-7
window.y=0
