package pl.khuzzuk.metadata;

import java.nio.file.Path;

public record SoundFileMetadata(
        String format,
        String path,
        String fileName,
        String indexedPath,
        String title,
        int rating,
        String date,
        String artist,
        String artists,
        String album,
        String albumArtist,
        String albumArtists,
        String composer,
        String conductor,
        String country,
        String custom1,
        String custom2,
        String custom3,
        String custom4,
        String custom5,
        String discNo,
        String genre,
        String group,
        String instrument,
        String mood,
        String movement,
        String occasion,
        String opus,
        String orchestra,
        String quality,
        String ranking,
        String tempo,
        String tonality,
        String track,
        String work,
        String workType) {
    public static SoundFileMetadata empty(Path path) {
        return empty(path, null);
    }

    public static SoundFileMetadata empty(Path path, Path indexedPath) {
        return new SoundFileMetadata(
                null,
                path == null ? null : path.toAbsolutePath().normalize().toString(),
                path == null || path.getFileName() == null ? null : path.getFileName().toString(),
                indexedPath == null ? null : indexedPath.toAbsolutePath().normalize().toString(),
                null,
                0,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null);
    }
}
